### ISSUE TITLE
ITK DB App - Crashed

### ISSUE THREAD

**Issue by Appzen-Joshua** [SAP-samples/btp-integration-toolkit-lite#1]
We are trying to build the ITK lite application. We followed the mission steps and when deploying the applications the DB services are crashing while the other two services are up and running. Attached is the error log.

DB service we were using is PostgreSQL and the service plan was standard.

Please let me know if you need any additional details.
[ItkApp-Db-ErrorLog.txt](https://github.com/SAP-samples/btp-integration-toolkit-lite/files/11739362/ItkApp-Db-ErrorLog.txt)

**Comment by gnshram** [comment]
Under Cloud Foundry deployed application, the DB will always be stopped. Only App and Services will be running. 
![image](https://github.com/SAP-samples/btp-integration-toolkit-lite/assets/128012205/362cd9f1-933e-4d15-ae8c-e0b5a1646323)
